[build]
builder = "nixpacks"
[build.phases]
  install = ["pip install -r requirements.txt", "apt-get update && apt-get install -y chromedriver"]
[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"